package com.horizone.pep_notes.ui.theme

import androidx.compose.ui.graphics.Color

val ForestPrimaryLight = Color(0xFF2E7D32)
val ForestOnPrimaryLight = Color(0xFFFFFFFF)
val ForestSecondaryLight = Color(0xFF8D6E63)
val ForestOnSecondaryLight = Color(0xFFFFFFFF)
val ForestBackgroundLight = Color(0xFFF5F9F0)
val ForestOnBackgroundLight = Color(0xFF1E3D00)
val ForestSurfaceLight = Color(0xFFF1F8E9)
val ForestOnSurfaceLight = Color(0xFF1A2C0C)
val ForestSurfaceVariantLight = Color(0xFFE3EDD8)
val ForestOnSurfaceVariantLight = Color(0xFF2E4600)

val ForestPrimaryDark = Color(0xFF81C784)
val ForestOnPrimaryDark = Color(0xFF00320A)
val ForestSecondaryDark = Color(0xFFA1887F)
val ForestOnSecondaryDark = Color(0xFF2D160F)
val ForestBackgroundDark = Color(0xFF0B1F0B)
val ForestOnBackgroundDark = Color(0xFFE8F5E9)
val ForestSurfaceDark = Color(0xFF102415)
val ForestOnSurfaceDark = Color(0xFFE0F2F1)
val ForestSurfaceVariantDark = Color(0xFF2E4630)
val ForestOnSurfaceVariantDark = Color(0xFFE0F2F1)

// Ocean theme
val OceanPrimaryLight = Color(0xFF1565C0)
val OceanOnPrimaryLight = Color(0xFFFFFFFF)
val OceanSecondaryLight = Color(0xFF00838F)
val OceanOnSecondaryLight = Color(0xFFFFFFFF)
val OceanBackgroundLight = Color(0xFFE3F2FD)
val OceanOnBackgroundLight = Color(0xFF001E3C)
val OceanSurfaceLight = Color(0xFFE0F7FA)
val OceanOnSurfaceLight = Color(0xFF00363A)
val OceanSurfaceVariantLight = Color(0xFFBBDEFB)
val OceanOnSurfaceVariantLight = Color(0xFF002F6C)

val OceanPrimaryDark = Color(0xFF90CAF9)
val OceanOnPrimaryDark = Color(0xFF002F6C)
val OceanSecondaryDark = Color(0xFF4DD0E1)
val OceanOnSecondaryDark = Color(0xFF00363A)
val OceanBackgroundDark = Color(0xFF001021)
val OceanOnBackgroundDark = Color(0xFFE3F2FD)
val OceanSurfaceDark = Color(0xFF001A33)
val OceanOnSurfaceDark = Color(0xFFE0F7FA)
val OceanSurfaceVariantDark = Color(0xFF294A6E)
val OceanOnSurfaceVariantDark = Color(0xFFCEE7FF)

// Desert theme
val DesertPrimaryLight = Color(0xFFEF6C00)
val DesertOnPrimaryLight = Color(0xFFFFFFFF)
val DesertSecondaryLight = Color(0xFF8D6E63)
val DesertOnSecondaryLight = Color(0xFFFFFFFF)
val DesertBackgroundLight = Color(0xFFFFF3E0)
val DesertOnBackgroundLight = Color(0xFF3B2710)
val DesertSurfaceLight = Color(0xFFFFE0B2)
val DesertOnSurfaceLight = Color(0xFF3B2710)
val DesertSurfaceVariantLight = Color(0xFFFFCC80)
val DesertOnSurfaceVariantLight = Color(0xFF4E342E)

val DesertPrimaryDark = Color(0xFFFFB74D)
val DesertOnPrimaryDark = Color(0xFF4E2600)
val DesertSecondaryDark = Color(0xFFD7CCC8)
val DesertOnSecondaryDark = Color(0xFF3E2723)
val DesertBackgroundDark = Color(0xFF2A1B0A)
val DesertOnBackgroundDark = Color(0xFFFFF3E0)
val DesertSurfaceDark = Color(0xFF3B2710)
val DesertOnSurfaceDark = Color(0xFFFFE0B2)
val DesertSurfaceVariantDark = Color(0xFF5D4037)
val DesertOnSurfaceVariantDark = Color(0xFFFFE0B2)

// Gotham theme
val GothamPrimaryLight = Color(0xFF212121)
val GothamOnPrimaryLight = Color(0xFFFFFFFF)
val GothamSecondaryLight = Color(0xFF424242)
val GothamOnSecondaryLight = Color(0xFFFFFFFF)
val GothamBackgroundLight = Color(0xFFFFFFFF)
val GothamOnBackgroundLight = Color(0xFF000000)
val GothamSurfaceLight = Color(0xFFFFFFFF)
val GothamOnSurfaceLight = Color(0xFF000000)
val GothamSurfaceVariantLight = Color(0xFFF5F5F5)
val GothamOnSurfaceVariantLight = Color(0xFF212121)

val GothamPrimaryDark = Color(0xFF000000)
val GothamOnPrimaryDark = Color(0xFFFFFFFF)
val GothamSecondaryDark = Color(0xFF9E9E9E)
val GothamOnSecondaryDark = Color(0xFFFFFFFF)
val GothamBackgroundDark = Color(0xFF121212)
val GothamOnBackgroundDark = Color(0xFFFFFFFF)
val GothamSurfaceDark = Color(0xFF1E1E1E)
val GothamOnSurfaceDark = Color(0xFFFFFFFF)
val GothamSurfaceVariantDark = Color(0xFF2D2D2D)
val GothamOnSurfaceVariantDark = Color(0xFFFFFFFF)
val GothamOutlineDark = Color(0xFF757575)
val GothamOutlineVariantDark = Color(0xFF5D5D5D)